# -*- coding: utf-8 -*-
"""ProgDataScienceFinalProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WE6c_LkQlL0O_jS7AyK1ZjXk_7qkatxv

**Step 1:** 	Set up a Git repository to allow you to collaborate on the Python solution

GIT hub repository is created and is available on below path
**https://github.com/bijoyvarghese001/ProgDataScienceFinalProject**

**Step 2:**	Read the daily confirmed cases and deaths into two dataframes can be found at this github page:
a)	confirmed_cases_url = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"
b)	deaths_url = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv"
"""

import pandas as pd

confirmed_cases_url = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"
deaths_url = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv"

confirmed_cases_df = pd.read_csv(confirmed_cases_url)
deaths_df = pd.read_csv(deaths_url)
print(confirmed_cases_df)
print(deaths_df)

"""**Step 3:** Use pandas to create a dataframe that aggregates and sums both confirmed cases and deaths on a global level"""

#global_confirmed_cases_df = confirmed_cases_df.groupby('Country/Region').sum().iloc[:, 4:]
#global_deaths_df = deaths_df.groupby('Country/Region').sum().iloc[:, 4:]

#global_df = pd.concat([global_confirmed_cases_df.sum(axis=0), global_deaths_df.sum(axis=0)], axis=1)
#global_df.columns = ['Confirmed Cases', 'Deaths']

# aggregate and sum the confirmed cases and deaths on a global level
global_confirmed_cases_df = confirmed_cases_df.iloc[:, 4:].sum(axis=0)
global_deaths_df = deaths_df.iloc[:, 4:].sum(axis=0)
global_df = pd.DataFrame({'Confirmed Cases': global_confirmed_cases_df, 'Deaths': global_deaths_df})
print(global_df)

"""**Step 4:**	Research a stock for each below that reflects the following industries (it will be used in the next step):
a)	Overall American Market
b)	Overall Canadian Market
c)	Travel sector
d)	The Real Estate sector
e)	Precious metals (Gold, Silver, Platinum, etc)

"""

import requests

apikey = '95NQ9UEXL1RBR75Z'

overall_american_market = 'AAPL'
overall_canadian_market = 'RY.TO'
travel_sector = 'DAL'
real_estate_sector = 'SPG'
precious_metals = 'GLD'



